name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write # ISSO É O MAIS IMPORTANTE
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.svg # Define o nome do arquivo
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_isocalendar: yes
          plugin_languages: yes
